`Literal` error while importing typing in line 2
In the recent update to the `typing` module, `Literal` has been excluded & included in `typing_extensions`.

## Issue
Getting the following error when running latest `doccano`.

```
File "/usr/local/lib/python3.6/dist-packages/app/api/models.py", line 3, in <module>
    from auto_labeling_pipeline.models import RequestModelFactory
  File "/usr/local/lib/python3.6/dist-packages/auto_labeling_pipeline/models.py", line 2, in <module>
    from typing import Dict, Literal, Optional, Type
ImportError: cannot import name 'Literal'
```